### ISSUE TITLE
Error when using colour import on Win10 Python 3.7.9

### ISSUE THREAD

**Issue by gennadyg** [colour-science/colour-demosaicing#20]
Hi,
Trying to  use your library for demosaic RAW16 -> RGB images and for some reason getting 'The specified module could not be found', despite the fact that installed all prerequisites listed and VC code can see **colour** package as locally installed, any help will be appreciated.

![image](https://user-images.githubusercontent.com/4568441/104165465-14c42a00-5402-11eb-8034-e5d6641f8c64.png)

![image](https://user-images.githubusercontent.com/4568441/104165880-a338ab80-5402-11eb-8e0c-c456e409cda9.png)

**Comment by KelSolaar** [comment]
Hi @gennadyg,

Can you let us know how you installed the package(s)? I'm not used to seeing the directory where the `colour.__init__` module resides on your system.

Cheers,

Thomas

**Comment by gennadyg** [comment]
Thanks for checking @KelSolaar,

Just followed github description with a following commands:

pip install --user colour-demosaicing
pip install --user colour-science

colour.__init_ located is here on my Win10: 
c:\Users\gegilin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\colour\__init__.py

Thanks.

**Comment by KelSolaar** [comment]
Cool!

Note that technically, only `pip install --user colour-demosaicing` should be needed as it will pull-down `colour-science-0.3.16` as a dependency.

Would it be possible to print `sys.path` from within your script and check that `c:\Users\gegilin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-package` is effectively listed?

At the top of your script:

```python

import sys
from pprint import pprint

pprint(sys.path)
```

**Comment by gennadyg** [comment]
Hi @KelSolaar 

That  what I'm getting from output in VS code(also added "import colour"):

`['c:\\IdeaProjects\\spark-rosbag\\src\\spark\\raw12_converter',
 'C:\\Program '
 'Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\\python37.zip',
 'C:\\Program '
 'Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\\DLLs',
 'C:\\Program '
 'Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\\lib',
 'C:\\Program '
 'Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0',
 'C:\\Users\\gegilin\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages',
 'C:\\Users\\gegilin\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\win32',
 'C:\\Users\\gegilin\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\win32\\lib',      
 'C:\\Users\\gegilin\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\Pythonwin',       
 'C:\\Program '
 'Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\\lib\\site-packages']
PS C:\IdeaProjects\spark-rosbag\src\spark\raw12_converter>  c:; cd 'c:\IdeaProjects\spark-rosbag\src\spark\raw12_converter'; & 'C:\Users\gegilin\AppData\Local\Microsoft\WindowsApps\python.exe' 'c:\Users\gegilin\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\lib\python\debugpy\launcher' '56550' '--' 'c:\IdeaProjects\spark-rosbag\src\spark\raw12_converter\Colour-demosaic-test.py' 
Traceback (most recent call last):
  File "c:\IdeaProjects\spark-rosbag\src\spark\raw12_converter\Colour-demosaic-test.py", line 3, in <module>
    import colour
  File "C:\Users\gegilin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\colour\__init__.py", line 57, in <module>
    from .adaptation import (CHROMATIC_ADAPTATION_METHODS,
  File "C:\Users\gegilin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\colour\adaptation\__init__.py", line 39, in <module>
  File "C:\Users\gegilin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\colour\adaptation\fairchild1990.py", line 23, in <module>
PS C:\IdeaProjects\spark-rosbag\src\spark\raw12_converter>  c:; cd 'c:\IdeaProjects\spark-rosbag\src\spark\raw12_converter'; & 'C:\Users\gegilin\AppData\Local\Microsoft\WindowsApps\python.exe' 'c:\Users\gegilin\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\lib\python\debugpy\launcher' '56566' '--' 'c:\IdeaProjects\spark-rosbag\src\spark\raw12_converter\Colour-demosaic-test.py' 
Traceback (most recent call last):
  File "c:\IdeaProjects\spark-rosbag\src\spark\raw12_converter\Colour-demosaic-test.py", line 3, in <module>
    import colour
  File "C:\Users\gegilin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\colour\__init__.py", line 57, in <module>
    from .adaptation import (CHROMATIC_ADAPTATION_METHODS,
  File "C:\Users\gegilin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\colour\adaptation\__init__.py", line 39, in <module>
    from .fairchild1990 import chromatic_adaptation_Fairchild1990
  File "C:\Users\gegilin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\colour\adaptation\fairchild1990.py", line 23, in <module>
    from colour.algebra import spow
  File "C:\Users\gegilin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\colour\algebra\__init__.py", line 16, in <module>
    from .interpolation import (
  File "C:\Users\gegilin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\colour\algebra\interpolation.py", line 65, in <module>
    import scipy.interpolate
  File "C:\Users\gegilin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\__init__.py", line 130, in <module>
    from . import _distributor_init
  File "C:\Users\gegilin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\_distributor_init.py", line 61, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
PS C:\IdeaProjects\spark-rosbag\src\spark\raw12_converter>`

Thanks,

**Comment by KelSolaar** [comment]
Hi @gennadyg,

Thanks, this is useful! So after unrolling the last line(s), I got this traceback:

```python
Traceback (most recent call last):

File "c:\IdeaProjects\spark-rosbag\src\spark\raw12_converter\Colour-demosaic-test.py",
    line 3, in <module> import colour 
File "C:\Users\gegilin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\colour\__init__.py",
    line 57, in <module> from .adaptation import (CHROMATIC_ADAPTATION_METHODS, 
File "C:\Users\gegilin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\colour\adaptation\__init__.py",
    line 39, in <module> from .fairchild1990 import chromatic_adaptation_Fairchild1990 
File "C:\Users\gegilin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\colour\adaptation\fairchild1990.py",
    line 23, in <module> from colour.algebra import spow 
File "C:\Users\gegilin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\colour\algebra\__init__.py",
    line 16, in <module> from .interpolation import ( 
    File "C:\Users\gegilin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\colour\algebra\interpolation.py",
        line 65, in <module> import scipy.interpolate 
File "C:\Users\gegilin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\__init__.py",
    line 130, in <module> from . import _distributor_init 
File "C:\Users\gegilin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\_distributor_init.py",
    line 61, in <module> WinDLL(os.path.abspath(filename)) 
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py",
    line 364, in __init__ self._handle = _dlopen(self._name, mode) OSError: [WinError 126] The specified module could not be found
```

It seems like your Scipy installation is somehow busted. Can you confirm you are able to `import scipy`?

Cheers,

Thomas

**Comment by gennadyg** [comment]
Hi Thomas,

Indeed have some environment problem about Scipy, unable to make `import scipy` with the same error, will investigate how to fix this in my environment.
Thanks a lot for pointing this out.
